// Predefined color options
let buttonColours = ["red", "blue", "green", "yellow"];

// The game pattern generated by the game
let gamePattern = [];

// The pattern clicked by the user
let userClickedPattern = [];

//You'll need a way to keep track of whether if the game has started or not, so you only call nextSequence() on the first keypress.
let started = false;

//2. Create a new variable called level and start at level 0.
let level = 0;

// Use jQuery to detect when a keyboard key has been pressed

$(document).keypress(function(){
    if(!started){
        $("#level-title").text("Level " + level);
        nextSequence();
        started = true;
    }
    
});


$(".btn").click(function(){
    let  userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);

    playSound(userChosenColour);
    animatePress(userChosenColour);
    checkAnswer(userClickedPattern.length-1);
});


function checkAnswer(currentLevel){
    if(userClickedPattern[currentLevel] === gamePattern[currentLevel]){
        console.log("succes");

        if (userClickedPattern.length === gamePattern.length) {
            setTimeout(function () {
                nextSequence();
            }, 1000);
        }
    }else{
        console.log("wrong");
        playSound("wrong")
        $("body").addClass("game-over")
        setTimeout(function(){
            $("body").removeClass("game-over")
        }, 200);

        $("#level-title").text("Game Over, Press Any Key to Restart")
        
        startOver();
    }
}


function nextSequence(){

    level++;

    $("#level-title").text("Level " + level);
    
    //
    let randomNumber = Math.floor(Math.random() * (4));

    let randomChosenColour = buttonColours[randomNumber];

    gamePattern.push(randomChosenColour);

    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    
    playSound(randomChosenColour);

};


function playSound(name){
    let btnAudio = new Audio("sounds/"+name+".mp3")
        btnAudio.play();
};


function animatePress(currentColour) {
    $("#"+ currentColour).addClass("pressed");

    setTimeout(function () {
        $("#"+ currentColour).removeClass("pressed");
    },50);
};


function startOver(){
    level = 0;
    gamePattern = [];
    started = false
}







